/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package helppackage;

import java.net.URI;

/**
 *
 * @author Administrator
 */
public class ModuleView extends javax.swing.JDialog {
    URI theUri;
    /**
     * Creates new form ModuleView
     */
    public ModuleView(java.awt.Frame parent, boolean modal,String description,String uri) {
        super(parent, modal);
        initComponents();
        try{
            theUri=new URI(uri);
            jButtonShow.setVisible(true);
        }
        catch(Exception ex)
        {
            jButtonShow.setVisible(false);
        }

        jLabelDisplay.setText(description);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonShow = new javax.swing.JButton();
        jButtonTakeMeaway = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Modules efficient settings:");

        jButtonShow.setText("Browse module");
        jButtonShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowActionPerformed(evt);
            }
        });

        jButtonTakeMeaway.setText("Close");
        jButtonTakeMeaway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTakeMeawayActionPerformed(evt);
            }
        });

        jLabelDisplay.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDisplay.setText("jLabel2");
        jLabelDisplay.setAutoscrolls(true);
        jLabelDisplay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelDisplay.setName("jLabelDisplay"); // NOI18N
        jLabelDisplay.setOpaque(true);
        jScrollPane1.setViewportView(jLabelDisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 333, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTakeMeaway)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonShow)
                    .addComponent(jButtonTakeMeaway))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowActionPerformed
        // TODO add your handling code here:
        DesktopHandler.launchUri(theUri);
        jButtonShow.setVisible(false);
    }//GEN-LAST:event_jButtonShowActionPerformed

    private void jButtonTakeMeawayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTakeMeawayActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonTakeMeawayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonShow;
    private javax.swing.JButton jButtonTakeMeaway;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDisplay;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
