package helppackage;

/**
 *
 * @author Administrator
 */
public class VersionDialog extends javax.swing.JDialog {
    Helper m_helper;
    /**
     * Creates new form VersionDialog
     */
    public VersionDialog(java.awt.Frame parent, boolean modal,Helper helper) {
        super(parent, modal);
        initComponents();
        m_helper=helper;
        getRootPane().setDefaultButton(jButtonClose);
        
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setVisible(false);
            }
        });
        
        jButtonGoToPage.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setVisible(false);
                m_helper.doWXTHome();
            }
        });
        
        jLabelGUIVersion.setText(m_helper.getFaceVersion());
        jLabelLatestGUIVersion.setText(m_helper.getLatestFaceVersion());
        jLabelEngineVersion.setText(m_helper.getWXTVersion());
        jLabelLatestEngineVersion.setText(m_helper.getLatestWXTVersion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelWXTGUI = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelGUIVersion = new javax.swing.JLabel();
        jLabelLatestGUIVersion = new javax.swing.JLabel();
        jPanelWXTEngine = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelEngineVersion = new javax.swing.JLabel();
        jLabelLatestEngineVersion = new javax.swing.JLabel();
        jButtonGoToPage = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("You are now running:");

        jPanelWXTGUI.setBackground(new java.awt.Color(255, 255, 204));
        jPanelWXTGUI.setBorder(javax.swing.BorderFactory.createTitledBorder("WXT Face"));

        jLabel2.setText("Version:");

        jLabel3.setText("Latest version:");

        jLabelGUIVersion.setText("jLabel6");

        jLabelLatestGUIVersion.setText("jLabel6");

        javax.swing.GroupLayout jPanelWXTGUILayout = new javax.swing.GroupLayout(jPanelWXTGUI);
        jPanelWXTGUI.setLayout(jPanelWXTGUILayout);
        jPanelWXTGUILayout.setHorizontalGroup(
            jPanelWXTGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWXTGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWXTGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(jPanelWXTGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLatestGUIVersion)
                    .addComponent(jLabelGUIVersion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWXTGUILayout.setVerticalGroup(
            jPanelWXTGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWXTGUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWXTGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelGUIVersion))
                .addGap(18, 18, 18)
                .addGroup(jPanelWXTGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelLatestGUIVersion))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanelWXTEngine.setBackground(new java.awt.Color(255, 255, 204));
        jPanelWXTEngine.setBorder(javax.swing.BorderFactory.createTitledBorder("WXT Engine"));

        jLabel4.setText("Version:");

        jLabel5.setText("Latest version:");

        jLabelEngineVersion.setText("jLabel6");

        jLabelLatestEngineVersion.setText("jLabel6");

        javax.swing.GroupLayout jPanelWXTEngineLayout = new javax.swing.GroupLayout(jPanelWXTEngine);
        jPanelWXTEngine.setLayout(jPanelWXTEngineLayout);
        jPanelWXTEngineLayout.setHorizontalGroup(
            jPanelWXTEngineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWXTEngineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWXTEngineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jPanelWXTEngineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLatestEngineVersion)
                    .addComponent(jLabelEngineVersion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelWXTEngineLayout.setVerticalGroup(
            jPanelWXTEngineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWXTEngineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWXTEngineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelEngineVersion))
                .addGap(18, 18, 18)
                .addGroup(jPanelWXTEngineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelLatestEngineVersion))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jButtonGoToPage.setText("Go to download page");

        jButtonClose.setText("Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jPanelWXTGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelWXTEngine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonGoToPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(jButtonClose)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanelWXTGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelWXTEngine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGoToPage)
                    .addComponent(jButtonClose))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonGoToPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelEngineVersion;
    private javax.swing.JLabel jLabelGUIVersion;
    private javax.swing.JLabel jLabelLatestEngineVersion;
    private javax.swing.JLabel jLabelLatestGUIVersion;
    private javax.swing.JPanel jPanelWXTEngine;
    private javax.swing.JPanel jPanelWXTGUI;
    // End of variables declaration//GEN-END:variables
}
